services:
  tgfeed:
    container_name: tgfeed
    image: ghcr.io/ndmitry/tgfeed:latest
    environment:
      - TZ=Europe/Moscow
      - HTTP_SERVER_PORT=8080
      - REDIS_HOST=redis
      # You can specify a custom HTML message for cases when the scraper
      # could not obtain the post content from t.me.
      # Use {postDeepLink} and {postURL} as placeholders for post links.
      # - UNSUPPORTED_MESSAGE_HTML
      # If you expirience problems with t.me access, try to change the UA
      # - USER_AGENT=
    ports:
      - 8080:8080
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - TZ=Europe/Moscow
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  redis-data:
