services:
  tgfeed:
    container_name: tgfeed
    build:
      context: .
      target: final
    volumes:
      - ./config.json:/app/config.json
      - ./feeds:/app/feeds
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
