name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: "*.sum"
        id: go

      - name: Get dependencies
        working-directory: ./
        run: go get -v -t -d ./...

      - name: Lint
        working-directory: ./
        run: go tool -modfile=go.tool.mod golangci-lint run ./...

      - name: Test
        working-directory: ./
        run: go test -v -race ./...
