name: Go Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache-dependency-path: "*.sum"
        id: go

      - name: Get dependencies
        working-directory: ./
        run: go get -v -t -d ./...

      - name: Lint
        working-directory: ./
        run: go tool -modfile=go.tool.mod golangci-lint run ./...

      - name: Test
        working-directory: ./
        run: go test -v -race ./...

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker tags
        id: prep
        run: |
          DOCKER_REPO="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "docker_repo=${DOCKER_REPO}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ steps.prep.outputs.docker_repo }}:latest
            ${{ steps.prep.outputs.docker_repo }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
